version: 2
build:
os: "ubuntu-22.04"
tools:
    python: "3.13"
commands:
    - pip install pydoctor
    - |
    pydoctor \
    --project-version=${READTHEDOCS_GIT_IDENTIFIER} \
    --project-url=${READTHEDOCS_GIT_CLONE_URL%*.git} \
    --html-viewsource-base=${READTHEDOCS_GIT_CLONE_URL%*.git}/tree/${READTHEDOCS_GIT_COMMIT_HASH} \
    --html-base-url=${READTHEDOCS_CANONICAL_URL} \
    --html-output $READTHEDOCS_OUTPUT/html/ \
    ./beniget