name: core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14-dev"]
          include:
          - name: Legacy Python on Ubuntu
            os: ubuntu-latest
            python-version: '3.6'
            use-docker: true
          - name: Legacy Python on Ubuntu
            os: ubuntu-latest
            python-version: '3.7'
            use-docker: true
          - name: Legacy Python on Ubuntu
            os: ubuntu-latest
            python-version: '3.8'
            use-docker: true
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      if: ${{ !matrix.use-docker }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: ${{ !matrix.use-docker }}
      run: |
        pip install -U pip
        pip install setuptools wheel pytest
    - name: Setup
      if: ${{ !matrix.use-docker }}
      run: |
        pip install .
    - name: Testing
      if: ${{ !matrix.use-docker }}
      run: |
        pytest --doctest-modules beniget/ tests/
    - name: Testing legacy
      if: ${{ matrix.use-docker }}
      run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:${{ matrix.python-version }} bash -c "
            python -m pip install -U pip setuptools wheel pytest
            python -m pip install .
            pytest --doctest-modules beniget/ tests/
          "
