name: core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
          python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
          include:
            - python-version: 2.7
              container: python:2.7.18-buster
            - python-version: 3.6
              os: ubuntu-20.04
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      if: ${{ ! ( matrix.python-version == '2.7' ) }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        test "${{ matrix.python-version }}" != "3.12-dev" || pip install setuptools
    - name: Setup
      run: |
        python setup.py install
    - name: Testing sequential
      run: |
        python setup.py test
