name: static

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  static_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install tox
      run: |
        python -m pip install --upgrade pip tox
    
    - name: Run mypy
      run: |
        tox -e mypy
    